### ISSUE TITLE
아티클 폼 작성

### ISSUE THREAD

**Issue by hoonpark7442** [hoonpark7442/railslation#11]
## 📖 개요
- 아티클 작성 페이지 구현

## 📝 상세 설명
- article 작성 폼 리팩토링
- 이미지 업로드 세팅 (액티브 스토리지)
- 리액트로 이미지 업로드 및 url 보여주기 기능

## ✅ To-Do 리스트

- [x] builder service
- [x] form view 리팩토링
- [x] 액티브 스토리지 configuration
- [x] 이미지 업로드 모델 세팅 
- [x] 이미지 업로드 컨트롤러 세팅
- [x] 리액트 공부 + 리액트 코드 분석
- [x] 리액트 이미지 업로드 컴포넌트 분석 및 필요 부분 추출(데브투 소스코드)
- [x] 리액트 이미지 url input 컴포넌트 추가
