### ISSUE TITLE
rss feed 번역 관련 뷰 작성

### ISSUE THREAD

**Issue by hoonpark7442** [hoonpark7442/railslation#32]
## 📖 개요
- 번역글일 경우의 메인 index, article show 수정
- rss feed 부분 뷰 작성

## 📝 상세 설명
- 기능 구현 관련 상세 설명

## ✅ To-Do 리스트

- [x] main index에 rss feed 5개 모아보기 섹션 추가 + CSS
- [x] rss feed approximately count 추가
- [x] rss feed view 
- [x] 번역글일 경우 번역 표시
