### ISSUE TITLE
(feature) 아티클 작성 기능 구현

### ISSUE THREAD

**Issue by hoonpark7442** [hoonpark7442/railslation#4]
## 📖 개요
- 아티클 모델 및 컨트롤러 세팅

## 📝 상세 설명
- 아티클 모델 구상 및 세팅 
- 컨트롤러 세팅

## ✅ To-Do 리스트

- [x] 아티클 모델 작성
- [x] 아티클에 인덱스 추가
- [x] 컨트롤러 index, create, edit, destory action 작성
- [x] redcarpet gem 세팅
- [x] 뷰 작성
