### ISSUE TITLE
article callback 세팅

### ISSUE THREAD

**Issue by hoonpark7442** [hoonpark7442/railslation#9]
## 📖 개요
- 아티클 저장 전 트리거되는 콜백함수들 추가

## 📝 상세 설명
- 부수 정보들 콜백함수 통해 세팅 및 저장

## ✅ To-Do 리스트

- [x] create slug
- [x] cached user 세팅
- [x] date 및 feautred number 세팅
- [x] hotness score 세팅
- [x] user_name 및 path 세팅
- [x] create password
- [x] touch collection
